### ISSUE TITLE
write_tif - shift in GIS program

### ISSUE THREAD

**Issue by HenzAndreas** [instructed-glacier-model/igm#16]
Tiff files coming from module `write_tif.py` have a shift when imported into a GIS program.

When a tiff file is generated by IGM using the `write_tif` post-processing module, the resulting tiff file has a small shift to the input data (see figure). The shift is probably due to the way the extension of the state variable (e.g. state.thk) is entered in the `rasterio` module for writing the tiff file.

This is of course **only relevant** if the IGM results are written as **tiff files** and used in a GIS program and has **no effect** on the **NetCDF** output. However, this is an issue, for example, when calculating differences to a palaeo-glacier reconstruction in GIS.

Appendix: Screenshot from QGIS. Imported tif from `tests/code-examples/aletsch-basic/` folder (model run from March 13, 2024). It can be seen that the eastern edges of Aletsch Glacier are too far to the east and the western edges are also too far to the east. This can be seen in the valley, but also on the ridges, where the ice on the eastern flanks starts further east than on the western flanks. (Background from swissALTI3D)

![aletsch-basic-thk-001900-reduced](https://github.com/jouvetg/igm/assets/127328141/cd4b8a68-cc03-47e3-8795-41cde21ccfe4)

**Comment by jouvetg** [comment]
Many thanks Andreas, this must be fixed, I have included in the todo list, but this may take a while, if any one has time to work on it, feel free to make a pull request ...

**Comment by HenzAndreas** [comment]
Fixed with PR#23 (bug fix, issue with shifted tif file when loading into QGIS now solved)
