### ISSUE TITLE
Avoid using dev branch if possible

### ISSUE THREAD

**Issue by fmaussion** [instructed-glacier-model/igm#17]
As discussed offline, I think that having a dev branch is more confusing than helping. All major projects I know have no dev branch, and this includes xarray, numpy, etc. 

It's not a big deal, but I do think that it brings confusion to new developers as to which branch to contribute to and where do bugfixes / improvements actually occur.

A commonly used development workflow would be:
- all development happens via pull-requests on main. Users are not guaranteed that latest main actually works as advertised, although normally continuous integration and testing should be a safeguard that tests are at least passing.
- if users want stability, they install a tagged version of the software (`pip install igm==x.y.z` or `pip install git+https://github.com/jouvetg/igm@x.y.z`). If they know their bug has been fixed on main, they install from latest main (`pip install git+https://github.com/jouvetg/igm`).
- all IGM developers open branches on their forks for development. Quick bugfixes lead to a pull-request which is merged quickly. Longer, more risky developments are still done on developer's branches: the pull-request is opened early in the process, but not merged until the feature is complete and tested. Multiple developers can still develop on the "feature" branch of the person who opened the pull-request. Users can find this feature on github and install it with `pip install git+https://github.com/john/igm@awesome_feature` or by pulling the developers fork.
- _igm should ideally not live on @jouvetg github but on an organization (this is not strictly necessary, but it would make it easier for Guillaume to have his own development branches)_

The current issue with the `dev` branch style chosen by IGM is that as of now, `develop` is 37 commits ahead of and 15 commits behind main. For external people like me its very unclear what to install if they want the "latest" version of the software. Will https://github.com/jouvetg/igm/issues/16 be fixed on main or dev? Why? At what point will it be decided to merge dev into main? etc.

Another advantage of having only one main branch and "features" pull-requests open from 1 hour to several months is that users can have a look at the list of pull-requests and see what is currently working on (for example a PR called "thermodynamics" or "mass-conservation" is much more obvious than a `develop` branch where several major changes might happen without users noticing. 

For completeness, I must note that very big projects such as numpy do have several branches in the central repository, for example `maintenance/1.19.x`. That's because numpy guaranties that they will continue to offer bugfixes (not new features) to certain version numbers for a period of time. When a bugfix is merged in `main` it might be ported ("cherry-picked") to the maintenance branches. Numpy is huge though: xarray has only one main branch and that's it.

To conclude this longer-than expected post, I don't think that the current workflow is harmful (there are probably some pros to this workflow as well, although I fail to see them since I've never worked on a project with a dev branch), but I for sure know it's confusing to people like me, who are more used to traditional github development workflows.

**Comment by fmaussion** [comment]
I actually came to writing this because I wanted to have a look at https://github.com/jouvetg/igm/issues/16. Which branch should I look to if I want to know the current state of `write_tiff.py`? `main`? `develop`? Normally, e.g. on xarray, I would have a look at the list of open PRs (is someone working on it?) and if not, I would look at the code on `main` to see what's needed to fix the issue. With the `develop` workflow I have to check both `main` and `develop`, and there is nothing in the open pull-requests.

**Comment by jouvetg** [comment]
Hello Fabien. Thanks for sharing your experience with code development. After some discussions, we finally came back to a single main branch, with tags for "stable" version, and who wants to have the latest feature would work directly at the end of the main branch.
