### ISSUE TITLE
IGM currently replaces NaNs in velocity field with 0s 

### ISSUE THREAD

**Issue by fmaussion** [instructed-glacier-model/igm#31]
I just saw this:

https://github.com/jouvetg/igm/blob/b8c57b4d643eb1987251f27ad374538903533913/igm/modules/preproc/oggm_shop/oggm_shop.py#L185-L186

Which means that even after I solved the issue upstream, IGM will still replace with 0s anyway.

Note also that ITSLIVE does not flags bad data or data outside glaciers with NaNs, but also has 0 (or very low) velocities.

If this is removed, it would be good to check if the outlier filtering happening further down is still working when NaNs are present:

https://github.com/jouvetg/igm/blob/b8c57b4d643eb1987251f27ad374538903533913/igm/modules/preproc/oggm_shop/oggm_shop.py#L209-L210

**Comment by jouvetg** [comment]
Thanks Fabien for spotting this! I must say that I did not realize this, we want to keep NaN when no obs available.. I have removed these lines replacing NaN by zeros, and also added a parameter (smooth_obs_vel, True by default) to allow not using this filtering. I have a made a tests, it does not seems to affect much the results (not many NaN in  the case I had as in many cases).
